[package]
name = "clone-gc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", optional = true, features = ["derive"] }
erased-serde = { version = "0.4.10", optional = true }
serde_json = { version = "1.0.149", optional = true }
clone-gc-macros = { workspace = true }

[dev-dependencies]
rand = "0.10.0"

[features]
default = ["iterative-drop", "serialization"]
iterative-drop = []
serialization = ["dep:serde", "dep:erased-serde", "dep:serde_json"]
